services:

  backend:
    image: maven:3.8.3-openjdk-17
    working_dir: /backend
    command: bash -c "mvn spring-boot:run"
    volumes:
      - ./backend/:/backend
    ports:
      - 8080:8080

  frontend:
    depends_on:
      - backend
    image: nginx
    ports:
      - 4200:80
    volumes:
      - ./frontend/:/usr/share/nginx/html